### ISSUE TITLE
Skip Current Day Altogether

### ISSUE THREAD

**Issue by melikarslan** [RoamJS/todo-trigger#1]
I want to tag new todos with creation date, like this: [[Date Created]]: {now}

But I don't want it to appear on todos that are already created in daily page because of redundancy. So I modified it as follows: [[Date Created]]{now:skip dnp}

But now, it always returns [[Date Created]]

Is there a way to get rid of this too? Like in my case: 
{[[Date Created]]:skip dnp} {now:skip dnp} didn't work, but is there any other way to do that?

And if there isn't, will you consider adding this feature? Thanks.

**Comment by dvargas92495** [comment]
I'm amenable to this feature

Current priority is to continue migrating the rest of RoamJS to Roam Depot - could circle back here after

**Comment by melikarslan** [comment]
Thanks!

**Comment by dvargas92495** [comment]
We now recommend the todo feature in smartblocks
